import { readFile, writeFile } from 'node:fs/promises';
import { BASE_CATALOG } from '../src/data/catalog.js';

const pages = JSON.parse(await readFile('research/source-images.json', 'utf8'));
const normalize = text => text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/^\d+[.\s–—-]*/, '').replace(/\s+/g, ' ').trim();
const aliases = {
  'Chin up': 'Chin up (barra fixa supinada)',
  'Crucifixo inverso': 'Crucifixo invertido com halteres',
  'Abdominal infra solo (abdominal inverso)': 'Abdominal infra solo (abdominal invertido)',
  'Abdominal lateral': 'Abdominal oblíquo',
  'Elevação frontal em Y': 'Elevação em Y',
  'Passada': 'Afundo',
  'Elevação pélvica': 'Como fazer a elevação de quadril corretamente',
  'Elevação pélvica com barra': 'Como fazer a elevação de quadril corretamente',
  'Extensão do quadril na polia': 'Coice glúteo na polia'
};
const details = {
  'Rosca spider': { equipment: 'Barra/halteres' },
  'Rosca Scott': { equipment: 'Barra/banco Scott/máquina' },
  'Desenvolvimento com barra': { mediaCaption: 'Demonstração sentado.' },
  'Crucifixo inverso': { mediaCaption: 'Demonstração com halteres.' },
  'Encolhimento': { mediaCaption: 'Demonstração com halteres.' },
  'Voador invertido': { mediaCaption: 'Demonstração na máquina.' },
  'Encolhimento por trás do corpo': { equipment: 'Barra/Smith', mediaCaption: 'Demonstração no Smith.' },
  'Agachamento sumô': { equipment: 'Barra/halteres/Smith', mediaCaption: 'Demonstração da variação no Smith.' },
  'Elevação frontal em Y': { mediaCaption: 'Demonstração com halteres e peito apoiado no banco.' },
  'Prancha abdominal': { mediaCaption: 'Sustente a posição: demonstração de um exercício isométrico.' }
};
const found = {};
const missing = [];
for (const exercise of BASE_CATALOG.filter(x => !x.gif)) {
  const name = normalize(aliases[exercise.name] || exercise.name);
  // Exact section-title matching; cross-page matches are limited to reviewed aliases.
  const candidates = pages.flatMap(page => page.images.map(image => ({ ...image, source: page.source })));
  let candidate;
  if (exercise.name === 'Prancha abdominal') candidate = candidates.find(x => x.source === 'https://fitnessprogramer.com/exercise/plank/' && x.alt === 'Plank' && x.url.endsWith('.gif'));
  else {
    const matches = candidates.filter(x => normalize(x.heading) === name && x.url.endsWith('.gif'));
    candidate = matches.find(x => x.source === exercise.source) || (aliases[exercise.name] ? matches[0] : undefined);
  }
  if (!candidate) { missing.push(exercise.name); continue; }
  found[exercise.id] = { gif: candidate.url, mediaSource: candidate.source, ...details[exercise.name] };
}
if (missing.length) throw new Error('Demonstrações ainda não encontradas: ' + missing.join(', '));
let index = 0;
const entries = Object.entries(found);
const verification = [];
async function verify() {
  while (index < entries.length) {
    const [id, item] = entries[index++];
    const response = await fetch(item.gif, { signal: AbortSignal.timeout(20000) });
    if (!response.ok) throw new Error(item.gif + ': HTTP ' + response.status);
    const data = new Uint8Array(await response.arrayBuffer());
    const signature = new TextDecoder().decode(data.slice(0, 6));
    if (!['GIF87a', 'GIF89a'].includes(signature)) throw new Error('Formato diferente de GIF: ' + item.gif);
    verification.push({ id, source: item.mediaSource, url: item.gif, bytes: data.length, signature });
  }
}
await Promise.all(Array.from({ length: 5 }, verify));
await writeFile('src/data/media-overrides.js', '// Demonstrations matched to source article sections. Generated by scripts/enrich-media.mjs.\nexport const MEDIA_OVERRIDES = ' + JSON.stringify(found, null, 2) + ';\n');
await writeFile('research/media-verification.json', JSON.stringify({ checkedAt: new Date().toISOString(), verification }, null, 2));
console.log('Demonstrações incluídas e verificadas: ' + entries.length);
